name: Java CI with Maven
on:
  pull_request:
    types: [closed]
  workflow_dispatch:



jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List Folder
      run: ls -lah
    - name: enter target
      run: cd target
    - name: results
      run: ls -lah

    - name: Get Version from pom.xml 
      id: get_version
      run: echo ::set-output name=version::$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}-JAVA11
        release_name: Release v${{ steps.get_version.outputs.version }} - JAVA11
        draft: false
        prerelease: false

    - name: Uploading Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/translator-${{ steps.get_version.outputs.version }}-jar-with-dependencies.jar
        asset_name: translator-${{ steps.get_version.outputs.version }}.jar
        asset_content_type: application/java-archive
